import { useRepo } from './RepoContext';
import {
  DEMO_REPO, DEMO_METRICS, DEMO_ARCHITECTURE_NODES,
  DEMO_ENV_VARIABLES, DEMO_SETUP_STEPS, DEMO_STARTER_TASKS,
} from './demo-data';

/**
 * Generates a complete ONBOARDING.md string from the current repo analysis.
 * Falls back to demo data when no live repo is loaded.
 */
export type ExportFormat = 'markdown' | 'script' | 'devcontainer';

export function useOnboardingExport(): {
  generate: (format?: ExportFormat) => string;
  generateSetupScript: () => string;
  generateDevContainer: () => string;
  download: (format?: ExportFormat) => void;
  repoName: string;
} {
  const { repoData } = useRepo();

  const repo = repoData?.repository || DEMO_REPO;
  const metrics = repoData?.metrics || DEMO_METRICS;
  const arch = (repoData?.architectureNodes?.length ?? 0) > 0
    ? repoData!.architectureNodes
    : DEMO_ARCHITECTURE_NODES;
  const envVars = (repoData?.envVariables?.length ?? 0) > 0
    ? repoData!.envVariables
    : DEMO_ENV_VARIABLES;
  const setup = (repoData?.setupSteps?.length ?? 0) > 0
    ? repoData!.setupSteps
    : DEMO_SETUP_STEPS;
  const tasks = (repoData?.starterTasks?.length ?? 0) > 0
    ? repoData!.starterTasks
    : DEMO_STARTER_TASKS;

  const repoName = `${repo.owner}/${repo.name}`;
  const isDemo = !repoData;

  function generateMarkdown(): string {
    const now = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });

    // --- Architecture as Mermaid ---
    const mermaidNodes = arch
      .filter(n => n.type !== 'external')
      .map(n => {
        const shape = n.type === 'database' ? `[(${n.label})]`
          : n.type === 'auth' ? `{${n.label}}`
          : `[${n.label}]`;
        return `    ${n.id}${shape}`;
      })
      .join('\n');

    const mermaidEdges = arch
      .flatMap(n => (n.children ?? []).map(childId => `    ${n.id} --> ${childId}`))
      .join('\n');

    const mermaid = `\`\`\`mermaid
flowchart TD
${mermaidNodes}
${mermaidEdges}
\`\`\``;

    // --- Setup steps ---
    const setupSection = setup.map(s => {
      const status = s.status === 'ok' ? '✅' : s.status === 'warning' ? '⚠️' : s.status === 'error' ? '❌' : '⏳';
      const cmd = s.command ? `\n\n  \`\`\`bash\n  ${s.command}\n  \`\`\`` : '';
      return `### ${status} ${s.label}\n${s.description || s.details || ''}${cmd}`;
    }).join('\n\n');

    // --- Env vars table ---
    const envHeader = `| Variable | Required | Description | Example |
|---|---|---|---|`;
    const envRows = envVars.map(v => {
      const req = v.required ? '✅ Yes' : '⚪ Optional';
      const desc = v.description?.replace(/\|/g, '\\|') || '—';
      const ex = (v.example || '').replace(/\|/g, '\\|');
      return `| \`${v.name}\` | ${req} | ${desc} | ${ex} |`;
    }).join('\n');

    // --- Starter tasks ---
    const diffIcon = (d: string) => d === 'beginner' ? '🟢' : d === 'intermediate' ? '🟡' : '🔴';
    const tasksSection = tasks.map((t, i) =>
      `### ${i + 1}. ${diffIcon(t.difficulty)} ${t.title} \`${t.difficulty.toUpperCase()}\`\n\n${t.description}\n\n**Why it matters:** ${t.whyItMatters}\n\n**Suggested next step:** ${t.nextStep}\n\n**Relevant files:**\n${t.relevantFiles.map(f => `- \`${f}\``).join('\n')}${t.estimatedTime ? `\n\n**Estimated time:** ${t.estimatedTime}` : ''}`
    ).join('\n\n---\n\n');

    // --- Tech stack from architecture ---
    const techStack = arch
      .filter(n => n.technology)
      .map(n => `| ${n.label} | ${n.technology} | ${n.type.charAt(0).toUpperCase() + n.type.slice(1)} |`)
      .join('\n');

    return `# ${repoName} — Developer Onboarding Guide
> Generated by [RepoPilot](https://github.com/repopilot) on ${now}${isDemo ? '\n> ⚠️ **Demo data** — analyze a real repository for accurate output.' : ''}

---

## 📋 Project Overview

| Field | Value |
|---|---|
| Repository | [\`${repoName}\`](${repo.url}) |
| Branch | \`${repo.branch}\` |
| Primary Language | ${repo.language || 'TypeScript'} |
| Total Files | ${metrics.totalFiles.toLocaleString()} |
| Lines of Code | ${(metrics.linesOfCode || 0).toLocaleString()} |
| Dependencies | ${metrics.dependencies} |
| API Routes | ${metrics.routes} |
| Modules | ${metrics.modules} |

${repo.description ? `> ${repo.description}` : ''}

---

## 🏗️ Architecture

${mermaid}

### Component Summary

${arch.map(n =>
  `- **${n.label}** (\`${n.type}\`)${n.technology ? ` — ${n.technology}` : ''}${n.description ? ` — ${n.description}` : ''}`
).join('\n')}

---

## 🛠️ Tech Stack

| Component | Technology | Layer |
|---|---|---|
${techStack}

---

## ⚙️ Local Setup

${setupSection}

---

## 🔐 Environment Variables

Copy the table below and populate your \`.env.local\` file:

${envHeader}
${envRows}

---

## 🚀 Starter Tasks for New Contributors

These tasks are AI-generated based on the actual repository structure and are ranked by difficulty.

${tasksSection}

---

## 📁 Key Entry Points

| Path | Purpose |
|---|---|
${arch.filter(n => n.filePath).map(n => `| \`${n.filePath}\` | ${n.label} |`).join('\n')}

---

*This guide was auto-generated by **RepoPilot** — the AI Developer Onboarding Agent.*
`;
  }

  function generateSetupScript(): string {
    const requiredEnvLines = envVars
      .filter(v => v.required)
      .map(v => `  check_env_var "${v.name}" "${v.example || ''}" "${v.description || ''}"`)
      .join('\n');

    const commandsToRun = setup
      .filter(s => s.command)
      .map(s => `echo "⚡ Running: ${s.command}..."\n${s.command}`)
      .join('\n\n');

    return `#!/usr/bin/env bash
# ==============================================================================
# Setup Script for ${repoName}
# Auto-generated by RepoPilot (AI Developer Onboarding Agent)
# ==============================================================================
set -e

echo "🚀 Setting up local environment for ${repoName}..."

# 1. Check Node.js runtime
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node 18+ (https://nodejs.org)."
    exit 1
fi

NODE_VERSION=$(node -v)
echo "✅ Node.js detected: $NODE_VERSION"

# 2. Setup Environment Variables
echo ""
echo "🔐 Configuring environment variables..."
if [ ! -f .env ] && [ -f .env.example ]; then
    echo "📋 Copying .env.example to .env..."
    cp .env.example .env
elif [ ! -f .env ]; then
    echo "⚠️  No .env file found. Creating default template..."
    cat << 'EOF' > .env
# Auto-generated environment file for ${repoName}
${envVars.map(v => `${v.name}=${v.example || ''}`).join('\n')}
EOF
    echo "✅ Created .env template with required keys."
fi

check_env_var() {
    local var_name="$1"
    local default_val="$2"
    local desc="$3"
    if ! grep -q "^$var_name=" .env 2>/dev/null; then
        echo "⚠️ Missing required env var: $var_name ($desc)"
    fi
}

${requiredEnvLines}

# 3. Install Dependencies
echo ""
echo "📦 Installing project dependencies..."
if [ -f "pnpm-lock.yaml" ]; then
    pnpm install
elif [ -f "yarn.lock" ]; then
    yarn install
else
    npm install
fi

# 4. Run Repo Setup Steps
echo ""
echo "⚙️ Executing project setup commands..."
${commandsToRun || 'echo "No additional setup commands required."'}

echo ""
echo "=============================================================================="
echo "🎉 Setup complete! You are ready to start contributing to ${repoName}."
echo "💡 Tip: Run RepoPilot dashboard anytime to view architecture & starter tasks."
echo "=============================================================================="
`;
  }

  function generateDevContainer(): string {
    const primaryLang = (repo.language || 'typescript').toLowerCase();
    const ports = [3000, 5000, 5173];

    const config = {
      name: `${repo.name} Dev Container`,
      image: 'mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye',
      forwardPorts: ports,
      features: {
        'ghcr.io/devcontainers/features/git:1': {},
        'ghcr.io/devcontainers/features/github-cli:1': {}
      },
      customizations: {
        vscode: {
          extensions: [
            'dbaeumer.vscode-eslint',
            'esbenp.prettier-vscode',
            'eamodio.gitlens',
            primaryLang.includes('python') ? 'ms-python.python' : 'biomejs.biome'
          ],
          settings: {
            'editor.formatOnSave': true,
            'editor.defaultFormatter': 'esbenp.prettier-vscode'
          }
        }
      },
      postCreateCommand: 'npm install',
      remoteUser: 'node'
    };

    return JSON.stringify(config, null, 2);
  }

  function generate(format: ExportFormat = 'markdown'): string {
    if (format === 'script') return generateSetupScript();
    if (format === 'devcontainer') return generateDevContainer();
    return generateMarkdown();
  }

  function download(format: ExportFormat = 'markdown') {
    const content = generate(format);
    const mimeMap: Record<ExportFormat, string> = {
      markdown: 'text/markdown',
      script: 'application/x-sh',
      devcontainer: 'application/json'
    };
    const filenameMap: Record<ExportFormat, string> = {
      markdown: 'ONBOARDING.md',
      script: 'setup.sh',
      devcontainer: 'devcontainer.json'
    };

    const blob = new Blob([content], { type: mimeMap[format] });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filenameMap[format];
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return { generate, generateSetupScript, generateDevContainer, download, repoName };
}
